### ISSUE TITLE
Cool

### ISSUE THREAD

**Issue by bherrmann7** [bvaughn/react-presents#1]
Hey this is really cool.     Thanks.     You should have something like,

       Thanks for walking through the demo

at the end of the demo.   It ends abruptly and I could not tell if it finished or if there was a bug.   

THANKS!

**Comment by bvaughn** [comment]
Thanks @bherrmann7 😁 I actually kind of ran out of steam on the demo site / docs b'c I've been traveling all weekend for a conference. I plan on elaborating more with the demo site soon. In the meanwhile though, yeah, good call. I'll add a closing slide!

**Comment by bvaughn** [comment]
Ending slide has been added 😉
