### ISSUE TITLE
Getting Uncaught Error

### ISSUE THREAD

**Issue by kirillku** [bvaughn/react-presents#10]
At some point, I started to get `Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of Presentation` in my project. I was trying to figure out what is wrong, I have reset all the changes in my project to the working version, but still the same error appears. Then, in vm, I have downloaded your repo, `npm install` and `npm start`. And again the same error.

![error](https://cloud.githubusercontent.com/assets/3331461/22642537/c17c3b26-ec63-11e6-9698-8fc541cea70e.png)

**Comment by bvaughn** [comment]
At first glance, it looks like react-router is the cause of this. It seems the API has changed since Alpha 5 and some of the exported components react-presents was relying on are no longer present.

**Comment by bvaughn** [comment]
For the time being, I would suggest pinning to an earlier version of react-router. If you'd be interested in submitting a PR that fixes this- I'd be happy to merge it and release. I won't have time to take a look for at least a couple of days though due to the fact that I'm traveling. My apologies.

**Comment by bvaughn** [comment]
Thank you for bringing this to my attention. I apologize for the amount of time it took me to get back to you with a fix, but I've been busy. Version 0.7.3 of react-presents has just been published. It supports the newer (4.0.0-beta.6 API) `react-router`/`react-router-dom` API.
