### ISSUE TITLE
Webpack 4 Compatibility?

### ISSUE THREAD

**Issue by IanWatt** [bvaughn/react-presents#21]
https://github.com/bvaughn/react-presents/blob/3837b53d842b11c2e1939053e968afa9c8f73594/source/modules/index.js#L7

Love the simplicity of this library. I think the lack of a default export in `./PropTypes` breaks compatibility with Webpack 4. Everything works fine with create-react-app 1.x, but not 2.x.

**Comment by bvaughn** [comment]
Hey Ian! I'm not quite sure why that import statement was written that way. Oversight? Wanna submit a PR fix?
