### ISSUE TITLE
Undocumented dependencies

### ISSUE THREAD

**Issue by AsaAyers** [bvaughn/react-presents#7]
I had to figure out that I need `react-addons-shallow-compare`, `react-router@4.0.0-alpha.6`, and `react-codemirror`

I'm not sure if these need to be added to `dependencies`, `peerDependencies`, or if the documentation needs updating.

My first experience with react-presents
========

I used `create-react-app` to make a presentation folder. I don't know if it matters, but I have `yarn` installed, so it would have used that instead of `npm install`.

I coped and pasted examples that seemed like it would get me a minimal presentation:

<details>
<summary>App.js</summary>

```js
import React from 'react';
import { Presentation, Slide, DropDownNav } from 'react-presents'

import Intro from './slides/intro'

const slides = [
    Intro
]

const options = slides
  .map((slide, index) => ({
    label: slide.title,
    value: index
  }))
  .filter((option) => option.label)

export default () => (
    <Presentation>
        {slides.map((Component, index) => (
            <Slide
                component={Component}
                key={index}
                />
        )).concat(
            <DropDownNav
                key='DropDownNav'
                options={options}
                />
        )}
    </Presentation>
)
```
</details>

<details>
<summary>slides/intro.js</summary>

```js
import React from 'react'
import { ContentSlide, Step } from 'react-presents'

export default () => (
  <ContentSlide>
    <h1>A simple slide</h1>
    <p>Slides can contain multiple steps.</p>
    <ul>
      <Step index={1} exact><li>Sub-text can appear only for a specific step</li></Step>
      <Step index={2}><li>Or it can be additive</li></Step>
      <Step index={3}><li>(By default it is additive)</li></Step>
      <Step index={4} maxIndex={5}><li>They can also be shown for a range</li></Step>
    </ul>
  </ContentSlide>
)
```
</details>

At this point it wouldn't compile because I was missing `react-addons-shallow-compare`, `react-router`, and `react-codemirror`. 

`yarn add react-addons-shallow-compare react-router react-codemirror` got the app to compile, but it doesn't work:

![selection_052](https://cloud.githubusercontent.com/assets/324999/21033894/cea44e3a-bd68-11e6-9b84-0e46523edb72.png)

After looking at the source for `react-presents` I realized I had to specify `react-router` v4. A `yarn add react-router@4.0.0-alpha.6` and now I have the example presentation.

**Comment by bvaughn** [comment]
Yikes. Sorry for the missing `dependencies` @AsaAyers. Actually fairly surprised that this went unnoticed for so long. Thanks for the issue report!

`react-addons-shallow-compare` will be a peer dep so you'll still need to install it manually (but at least NPM will tip you off about this). I've moved the other 2 from dev deps to deps so they'll auto-install for you. 😄

**Comment by bvaughn** [comment]
Fixed in 0.7.2!

**Comment by mike3run** [comment]
I'm still running into this issue tried yesterday and also today.

First with a NextJS project and now with a react boilerplate project :(

**Comment by bvaughn** [comment]
Need more info, @mike3run
